export const SEND_REQUEST_WALLET = 'SEND_REQUEST_WALLET'
export const STOP_REQUEST_WALLET = 'STOP_REQUEST_WALLET'
export const SAVE_WALLET_INFO = 'SAVE_WALLET_INFO'
export const ADD_CASH = 'ADD_CASH'
export const SUBTRACT_E_MONEY = 'SUBTRACT_E_MONEY'
export const TRANSFER_CASH_TO_ELECTRONIC = 'TRANSFER_CASH_TO_ELECTRONIC'
export const CLEAR_WALLET = 'CLEAR_WALLET'
export const CATCH_ERROR_WALLET = 'CATCH_ERROR_WALLET'

