
export const REQUEST_ACTIVE_COMBOS = 'REQUEST_ACTIVE_COMBOS'
export const STOP_REQUEST_ACTIVE_COMBOS = 'STOP_REQUEST_ACTIVE_COMBOS'
export const CATCH_ERROR_ACTIVE_COMBOS = 'CATCH_ERROR_ACTIVE_COMBOS' 

export const RECEIVE_ACTIVE_COMBOS = 'RECEIVE_ACTIVE_COMBOS'
export const RECEIVE_DETAIL_COMBO = 'RECEIVE_DETAIL_COMBO'
export const RECEIVE_POLICIES = 'RECEIVE_POLICIES'