export const serverURL = 'https://dnguyen-combo-manager.herokuapp.com'
export const coreURL = 'https://waza-passenger.herokuapp.com'
export const rewardURL = 'https://safe-caverns-44957.herokuapp.com'
export const paymentURL = 'https://waza-payment.herokuapp.com'
export const formatOfDateFromDB = 'YYYY/MM/DD'
export const dateFormat = 'DD/MM/YYYY' 
export const cookieName = 'user-waza-membership'