export const SEND_REQUEST = 'SEND_REQUEST_MY_COMBO'
export const STOP_REQUEST = 'STOP_REQUEST_MY_COMBO'
export const RECEIVE_BOUGHT_COMBO = 'RECEIVE_BOUGHT_COMBO'
export const STOP_AUTO_RENEW = 'STOP_AUTO_RENEW'
export const AUTO_RENEW = 'AUTO_RENEW'
export const RECEIVE_MY_COMBOS = 'RECEIVE_MY_COMBOS'
export const CATCH_ERROR_MY_COMBO = 'CATCH_ERROR_MY_COMBO'
export const CLEAR_MY_COMBOS = 'CLEAR_MY_COMBOS'

