export const SEND_REQUEST = 'SEND_REQUEST'
export const STOP_REQUEST = 'STOP_REQUEST'
export const RECEIVE_BOUGHT_COMBO = 'RECEIVE_BOUGHT_COMBO'
export const STOP_COMBO = 'STOP_COMBO'
export const RECEIVE_MY_COMBOS = 'RECEIVE_MY_COMBOS'

